# Numpy

In [ ]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [ ]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [ ]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [ ]:
np.array([3 for i in np.arange(100)])

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [ ]:
help(np.add)

#### 5. Поменять 2 строки в матрице

In [ ]:
a = np.diag([1,2])
a[[i for i in range(a.shape[0])], :] = a[[i for i in reversed(range(a.shape[0]))], :]
a

array([[0, 2],
       [1, 0]])

#### 6. Создать вектор со значениями от 10 до 100

In [ ]:
a = np.array([i for i in np.arange(10, 101)])
a

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [ ]:
np.flip(a)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [ ]:
np.arange(0,16).reshape(4,4) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
a = np.zeros((5, 4))
a[:, 0] = np.arange(1,6)
a = a.reshape(20)
a

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

#### 10. Создать 3x3 единичную матрицу

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [ ]:
np.random.rand(3,3,3)

array([[[0.87632731, 0.77062508, 0.63889988],
        [0.36138024, 0.05892663, 0.69720791],
        [0.54009331, 0.8220994 , 0.93502444]],

       [[0.06469145, 0.55768173, 0.56579293],
        [0.02165326, 0.5442317 , 0.02793711],
        [0.27894284, 0.20307334, 0.06627557]],

       [[0.98657958, 0.16992259, 0.12053315],
        [0.06336376, 0.98101534, 0.0420458 ],
        [0.77241773, 0.7923828 , 0.425788  ]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [ ]:
a = np.random.rand(10, 10)
print("min is {0} \nmax is {1}".format(np.min(a), np. max(a)))

min is 0.03165242368423571 
max is 0.9981832896077117


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
np.mean(np.random.rand(30))

0.4624741079447698

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [ ]:
#фурье
np.fft.fft(np.exp(2j * np.pi * np.arange(8) / 8))

array([-3.44509285e-16+1.14423775e-17j,  8.00000000e+00-8.11483250e-16j,
        2.33486982e-16+1.22464680e-16j,  0.00000000e+00+1.22464680e-16j,
        9.95799250e-17+2.33486982e-16j,  0.00000000e+00+7.66951701e-17j,
        1.14423775e-17+1.22464680e-16j,  0.00000000e+00+1.22464680e-16j])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [ ]:
a = np.zeros((5,5))
t = np.array([1,2,2,4])
for i in np.arange(a.shape[0]-1):
  a[i+1, i] = t[i]

a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [ ]:
np.array([(i % 2 + (i//8) % 2) % 2 for i in np.arange(64)]).reshape((8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [ ]:
a = np.array([i for i in range(6*7*8)]).reshape(6,7,8)
x, y, z = np.where(a == 99)
print(x, y, z)

[1] [5] [3]


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
np.tile([[0,1],[1,0]], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [ ]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)

a@b

array([[0.67856532, 0.91621271],
       [1.19101918, 1.18395199],
       [1.54472322, 1.7645498 ],
       [1.36292317, 1.06363791],
       [0.45328271, 0.88278385]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
a = np.arange(10)
a[(a >= 3) & (a <= 8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [ ]:
a = np.array([i for i in range(5)]*5).reshape(5,5)
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [ ]:
def countdown(num):
     while num > 0:
         yield num
         num -= 1

val = countdown(5)
a = []

for i in range(5):
  a.append(next(val))

a = np.array(a)
a

array([5, 4, 3, 2, 1])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [ ]:
np.linspace(0, 1, 10, endpoint=False)[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 26. Отсортировать вектор

In [ ]:
a = np.random.randint(0, 10, 10)
sorted(a)

[0, 0, 2, 4, 4, 4, 5, 5, 6, 8]

#### 27. Проверить, одинаковы ли 2 numpy массива

In [ ]:
a = np.arange(0,10)
b = np.arange(0,10)
np.array_equal(a,b)

True

#### 28. Сделать массив неизменяемым

In [ ]:
a = np.zeros(10)
a.flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [ ]:
n = 7
a = np.random.randint(0, 10, 20)
sorted(a, reverse=True)[0:n]

[9, 8, 7, 6, 6, 6, 6]

#### 30. Заменить максимальный элемент на ноль

In [ ]:
a = np.random.randint(0, 10, 10)
mask = np.where(a == max(a))[0]
a[mask] = 0
a

array([5, 6, 0, 4, 6, 6, 3, 4, 4, 6])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [ ]:
x = np.linspace(0, 1, 30)
y = np.linspace(0, 1, 30)

X, Y = np.meshgrid(x, y)

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [ ]:
a = np.array([1, 3, 2, 1])
b = np.array([1, 1, 4, 8, 8])

t_a = np.array([i for i in a] * b.shape[0]).reshape(a.shape[0], b.shape[0])
t_b = np.array([i for i in b] * a.shape[0]).reshape(b.shape[0], a.shape[0]).T

C = 1 / ((t_a + t_b) + 1e-10)
C

array([[0.5       , 0.09090909, 0.1       , 0.2       , 0.5       ],
       [0.25      , 0.33333333, 0.11111111, 0.11111111, 0.14285714],
       [0.16666667, 0.5       , 0.5       , 0.09090909, 0.1       ],
       [0.11111111, 0.2       , 0.25      , 0.33333333, 0.11111111]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
a = [np.int8,
np.int16,
np.int32,
np.int64,
np.uint8,
np.uint16,
np.uint32,
np.uint64,
np.intp,
np.uintp]

for i in a:
  print(np.iinfo(i))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------

Machine parameters for uint16
-----------------------------

#### 34. Напечатать все значения в массиве

In [ ]:
a = np.arange(10)

for i in a:
  print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
a = np.arange(10)
value = 4.6
a[(np.abs(a - value)).argmin()]

5

#### 36. Преобразовать массив из float в int

In [ ]:
np.arange(10).astype(float).astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 37. Каков эквивалент функции enumerate для np массивов?

In [ ]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 38. Случайно расположить p элементов в 2D массив

In [ ]:
a = np.zeros(100)
p = 30

mask = np.random.randint(0, 100, p)
a[mask] = 1

a.reshape(10,10)

array([[0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 1., 0., 1., 0., 1.]])

#### 39. Отнять среднее из каждой строки в матрице

In [ ]:
a = np.random.randint(0,10,90).reshape(9,10)
t = np.mean(a, axis=1).reshape(9,1)

a - t

array([[-0.6,  0.4,  1.4,  0.4, -1.6,  1.4, -1.6,  0.4, -2.6,  2.4],
       [ 0.7,  1.7, -1.3,  2.7, -2.3,  0.7, -2.3,  0.7,  2.7, -3.3],
       [ 0.5,  3.5,  2.5, -1.5,  2.5,  2.5, -4.5, -2.5,  0.5, -3.5],
       [ 3.6, -3.4,  3.6,  2.6, -0.4,  0.6, -1.4, -2.4, -4.4,  1.6],
       [-3.3, -1.3,  3.7,  1.7,  1.7,  3.7, -5.3, -3.3,  3.7, -1.3],
       [-1.6, -2.6, -2.6,  3.4, -3.6, -0.6, -1.6,  5.4,  5.4, -1.6],
       [ 1. ,  4. , -4. , -1. ,  4. , -3. , -3. , -1. ,  0. ,  3. ],
       [-4.5, -4.5,  0.5, -0.5,  4.5, -0.5, -2.5,  3.5,  0.5,  3.5],
       [ 3.9, -1.1,  0.9, -0.1,  2.9,  2.9,  0.9, -0.1, -5.1, -5.1]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [ ]:
a = np.random.randint(0, 10, 100).reshape(10,10)
n = 1
print(a)

a = a[np.argsort(a[:, n-1])]
print()
print(a)

[[9 8 0 5 8 5 4 2 2 3]
 [0 7 7 3 4 4 8 0 7 0]
 [5 4 2 5 8 3 5 8 5 3]
 [5 1 9 4 7 4 4 5 5 9]
 [9 7 1 4 9 1 5 7 5 5]
 [1 1 3 5 9 4 6 9 4 4]
 [0 3 1 2 5 9 8 6 0 0]
 [0 4 2 9 7 4 1 5 8 9]
 [7 8 3 4 7 8 6 1 6 6]
 [6 8 6 8 9 2 6 7 0 9]]

[[0 7 7 3 4 4 8 0 7 0]
 [0 3 1 2 5 9 8 6 0 0]
 [0 4 2 9 7 4 1 5 8 9]
 [1 1 3 5 9 4 6 9 4 4]
 [5 4 2 5 8 3 5 8 5 3]
 [5 1 9 4 7 4 4 5 5 9]
 [6 8 6 8 9 2 6 7 0 9]
 [7 8 3 4 7 8 6 1 6 6]
 [9 8 0 5 8 5 4 2 2 3]
 [9 7 1 4 9 1 5 7 5 5]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [ ]:
a = np.ones((3,3))
a[2, :] = 0

for i in np.arange(a.shape[0]):
  

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.]])

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [ ]:
mask = [1,2,3,4,6]

a = np.zeros(10)
np.add.at(a, mask, 1)
a

array([0., 1., 1., 1., 1., 0., 1., 0., 0., 0.])

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [ ]:
w = 5
h = 5

a = np.random.randint(255, size=(w,h,3))
np.unique(a).shape[0]

68

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
a.reshape(2, 8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [ ]:
a.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [ ]:
a.reshape(2,2,2,2).sum(axis = 2)

array([[[ 4,  6],
        [12, 14]],

       [[20, 22],
        [28, 30]]])

In [ ]:
a.reshape(2,2,2,2).sum(axis = 3)

array([[[ 3,  7],
        [11, 15]],

       [[19, 23],
        [27, 31]]])